Class {
	#name : 'MicRuleHeaderCheckStrategy',
	#superclass : 'Object',
	#instVars : [
		'checker'
	],
	#category : 'Microdown-Doc-Rules-Capitalization',
	#package : 'Microdown-Doc-Rules',
	#tag : 'Capitalization'
}

{ #category : 'accessing' }
MicRuleHeaderCheckStrategy >> checker [

	^ checker
]

{ #category : 'accessing' }
MicRuleHeaderCheckStrategy >> checker: anObject [

	checker := anObject
]
